@using System.Runtime.ExceptionServices
@model RestSupplyMVC.ViewModels.CustomerOrderViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer Order Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KitchenName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KitchenName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <table class="table table-striped table-responsive" id="supIng">
            <hr />
            @if (Model.CustomerOrderDetailsList.Any())
            {
                <h5> <b>Menu Items:</b></h5>
                <tr>
                    <td>
                        <b>@Html.DisplayNameFor(model => model.CustomerOrderDetailsList.First().Name)</b>
                    </td>
                    <td>
                        <b>  @Html.DisplayNameFor(model => model.CustomerOrderDetailsList.First().Quantity)</b>
                    </td>
                </tr>
                foreach (var item in Model.CustomerOrderDetailsList)
                 {
                     <tr>
                         <td>
                             @Html.DisplayFor(modelItem => item.Name)
                         </td>
                         <td>

                             @Html.DisplayFor(model => item.Quantity)
                         </td>
                     </tr>

                 }
            }
            else
            {
                     <h3> <b>No Menu Items!</b></h3>
            }
        </table>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", new { kitchenId = Model.KitchenId})
</p>
